import Head from 'next/head'
import { Tabs, Layout } from 'antd'
import { Home as Index } from '@styles/pages'
import wrapper from '@store/index'

const { TabPane } = Tabs
const { Content } = Layout

export const getServerSideProps = wrapper.getStaticProps(
	(store) => async (context) => {
		return {
			props: {},
		}
	},
)

export default function Home() {
	const onChangeTab = (key: string) => {
		console.log('탭 전환', key)
	}

	return (
		<Content className="main">
			<Index>
				<Head>
					<title>Create Next App</title>
					<meta
						name="description"
						content="Generated by create next app"
					/>
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<p>index 페이지 입니다.</p>
			</Index>
		</Content>
	)
}
