import Head from 'next/head'
import { Tabs, Layout } from 'antd'
import { Home as Index } from '@styles/pages'

const { TabPane } = Tabs
const { Content } = Layout

export default function Home() {
	const onChangeTab = (key: string) => {
		console.log('탭 전환', key)
	}

	return (
		<Content className="main">
			<Index>
				<Head>
					<title>Create Next App</title>
					<meta
						name="description"
						content="Generated by create next app"
					/>
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Tabs defaultActiveKey="1" type="card" onChange={onChangeTab}>
					<TabPane tab="Tab 1" key="1">
						<Content>Content of Tab Pane 1</Content>
					</TabPane>
					<TabPane tab="Tab 2" key="2">
						<Content>Content of Tab Pane 2</Content>
					</TabPane>
					<TabPane tab="Tab 3" key="3">
						<Content>Content of Tab Pane 3</Content>
					</TabPane>
				</Tabs>
			</Index>
		</Content>
	)
}
